---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: resourceUS
      name: Server2016
      os_type: Windows
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: P@ssw0rd123!
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2016-Datacenter'
        version: latest
